### ISSUE TITLE
rtk-query requires react type definitions (not framework-agnostic)

### ISSUE THREAD

**Issue by lacolaco** [rtk-incubator/rtk-query#138]
I've tried to use RTK-Query in an Angular/Redux-Toolkit project but it requires type definitions from react and react-redux, which seems to be for Hooks support.

```
    node_modules/@rtk-incubator/rtk-query/dist/ts/react-hooks/module.d.ts:21:30 - error TS2307: Cannot find module 'react-redux'.
    
    21     useStore?: typeof import('react-redux').useStore;
                                    ~~~~~~~~~~~~~
    node_modules/@rtk-incubator/rtk-query/dist/ts/react-hooks/ApiProvider.d.ts:1:25 - error TS2307: Cannot find module 'react'.
    
    1 import { Context } from 'react';
                              ~~~~~~~
    node_modules/@rtk-incubator/rtk-query/dist/ts/react-hooks/ApiProvider.d.ts:2:40 - error TS2307: Cannot find module 'react-redux'.
    
    2 import { ReactReduxContextValue } from 'react-redux';
                                             ~~~~~~~~~~~~~
    node_modules/@rtk-incubator/rtk-query/dist/ts/react-hooks/ApiProvider.d.ts:16:5 - error TS2503: Cannot find namespace 'JSX'.
    
    16 }): JSX.Element;
           ~~~
```

Is this by design?

![image](https://user-images.githubusercontent.com/1529180/103431695-af10ba80-4c17-11eb-8d55-3180b61c4681.png)

**Comment by markerikson** [comment]
Nope.  This is, as clearly labeled, still an experimental alpha, and thus subject to both bugs and unstable changes :)  @phryneas just got done trying to rearrange one of the core APIs to be more UI-agnostic, but it's entirely possible something got missed.

Can you post a project that reproduces the issue?

**Comment by lacolaco** [comment]
Sure. Here it is. https://github.com/lacolaco/rtkquery-playground

1. `yarn install`
2. `yarn build`
3. Errors!

Wishing you a Happy New Year!

**Comment by phryneas** [comment]
Could you try it with the platform-agnostic `createBaseApi` entrypoint? `createApi` contains the react-redux hooks. We might rename that to `createReactHooksApi` but I didn't want to introduce any breaking changes between alpha 1 & 2.

**Comment by phryneas** [comment]
Hmm. Just tried it. At runtime, this would do it.
But this is a type error. The question is how we can get TypeScript not to complain when a file (that might not get called at all) tries to import types from an optional dependency.
Most projects I've been working on just have `skipLibChecks: true`, but that should not be the only way to get around this :/
(And I'd want to avoid copying parts of other typings into our definitions just for that)

**Comment by phryneas** [comment]
Even removing all type references, the angular bundler seems to get picky here.

I'd expect an import statement with a missing target to just return `undefined`, not stop the bundler. We'll maybe have to resolve to `require` calls here then?

Maybe we also just need a different entrypoint altogether.

One weird thing though: The compilation process seems to insert `import 'react'` at completely random places in files that have nothing to do with react at all? Thank you TypeScript I guess... I have no idea.

I'll try to get around to this and further investigate within the next few days - sorry for the hassle. (So far, it has been working fine with our svelte examples)

**Comment by phryneas** [comment]
@lacolaco you can try the codesandbox build over at #141 - I believe that should solve this issue for you.

**Comment by lacolaco** [comment]
@phryneas I tried to apply that patch to my playground and most of the missing type definition errors are fixed. Remaining is only the below:

![image](https://user-images.githubusercontent.com/1529180/103449422-8659f500-4ceb-11eb-98e3-a71cb5dfffe4.png)

**Comment by lacolaco** [comment]
Perhaps `@ts-ignore` directive doesn't solve the error from missing modules...

**Comment by phryneas** [comment]
@lacolaco it would do, but apparently only as `// @ts-ignore`, not as `/* @ts-ignore */` unfortunately, those are stripped on the build step. 

I'll look further into this, but for now I'll wait for the feedback from this:
https://twitter.com/AndaristRake/status/1345151395784253440

Because right now, TS is complaining about a file that is definitely not imported and he's right, that should not really be the case.

**Comment by lacolaco** [comment]
@phryneas yeah, you're right. It now emits no errors after edited the comment from /* @ts-ignore */` to `// @ts-ignore`. Interesting.

**Comment by phryneas** [comment]
@lacolaco btw., looking forward for feedback from an Angular perspective :)

Also, you can extend `createApi` like we do it for the react hooks if there are repeated abstractions you'd want to make: https://rtk-query-docs.netlify.app/concepts/customizing-create-api

**Comment by lacolaco** [comment]
Thanks! 

I'm interested in the collaboration between RTK and NgRx ecosystem, and to integrate RTK-Query with Angular, key concepts are two, RxJS and Dependency Injection. If it can be interop to NgRx, I think it will be easy to achieve. Currently, RTK-Query's middlewares aren't compatible with NgRx's store API. 
So, I'm finding a way to connect `configureStore` and NgRx's `StoreModoule.forRoot`.

**Comment by phryneas** [comment]
So, yeah, @Andarist found it. One stray type reference from the core module into the react module :facepalm: . Now the CSB build should be working: 

`yarn add https://pkg.csb.dev/rtk-incubator/rtk-query/commit/fec237a0/@rtk-incubator/rtk-query`

**Comment by lacolaco** [comment]
Cool! I've confirmed now that works without any warning suppressions!

**Comment by msutkowski** [comment]
This is awesome! Thanks @andarist for the help. @lacolaco if you need any help experimenting with the ngrx integration, let me know! I know someone on that team that can potentially help us out
